export const Questions = [
  {
    prompt: "What is 4*50?",
    optionA: "200",
    optionB: "2100",
    optionC: "2000",
    optionD: "150",
    answer: "A",
  },
  {
    prompt: "Which is the best social platform for job search?",
    optionA: "Twitter",
    optionB: "Instagram",
    optionC: "Facebook",
    optionD: "LinkedIn",
    answer: "D",
  },
  {
    prompt: "What is 4+6?",
    optionA: "20",
    optionB: "10",
    optionC: "200",
    optionD: "6",
    answer: "B",
  },
  {
    prompt: "Which is your fav color?",
    optionA: "Pink",
    optionB: "Blue",
    optionC: "White",
    optionD: "Green",
    answer: "D",
  },
  {
    prompt: "What you like?",
    optionA: "Cricket",
    optionB: "Tennis",
    optionC: "Football",
    optionD: "Chess",
    answer: "C",
  },
  {
    prompt: "What does HTML stand for??",
    optionA: "Hyper Text Markup Language",
    optionB: "Home Tool Markup Language",
    optionC: "Hyperlinks and Text Markup Language",
    optionD: "Hyperlinks and Text Markup",
    answer: "A",
  },
  {
    prompt: "Choose the correct HTML element for the largest heading:",
    optionA: "<heading>",
    optionB: "<head>",
    optionC: "<h1>",
    optionD: "h6",
    answer: "C",
  },
  {
    prompt: "What is the correct HTML element for inserting a line break?",
    optionA: "<br>",
    optionB: "<head>",
    optionC: "<break>",
    optionD: "<lb>",
    answer: "A",
  },
  {
    prompt: "Which character is used to indicate an end tag?",
    optionA: "^",
    optionB: "/",
    optionC: "<",
    optionD: "*",
    answer: "B",
  },
  {
    prompt: "How can you make a numbered list?",
    optionA: "<ul>",
    optionB: "<list>",
    optionC: "<ol>",
    optionD: "<dl>",
    answer: "C",
  },
];
